/*
 Snapshot Isolation(SI) - each transaction work with consistent snapshot
of the data at a particular point in time. Snapshot contains all
actual committed data before the moment of it's creation.
SI have minimum blocks, in fact block only repeatable changes the same row.

 SHOW DEFAULT_TRANSACTION_ISOLATION; = read committed
 */

CREATE TABLE accounts
(
    id     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client text,
    amount numeric
);
INSERT INTO accounts
VALUES (1, 'alice', 1000.00),
       (2, 'bob', 100.00),
       (3, 'bob', 900.00);

BEGIN;
UPDATE accounts SET amount = amount - 200 WHERE id  = 1;
SELECT * FROM accounts WHERE client = 'alice';
COMMIT;

